python probability_gpt.py stimuli/sent_send_ce_eykey.txt result/prob_gpt_sent_send_ce_eykey.txt
python probability_gpt.py stimuli/sent_send_cehuy_hanthey.txt result/prob_gpt_sent_send_cehuy_hanthey.txt
python probability_gpt.py stimuli/sent_send_cehuy_eykey.txt result/prob_gpt_sent_send_cehuy_eykey.txt
python probability_gpt.py stimuli/sent_send_ce_hanthey.txt result/prob_gpt_sent_send_ce_hanthey.txt

python probability_bert.py stimuli/sent_send_ce_eykey.txt result/prob_bert_sent_send_ce_eykey.txt
python probability_bert.py stimuli/sent_send_cehuy_hanthey.txt result/prob_bert_sent_send_cehuy_hanthey.txt
python probability_bert.py stimuli/sent_send_cehuy_eykey.txt result/prob_bert_sent_send_cehuy_eykey.txt
python probability_bert.py stimuli/sent_send_ce_hanthey.txt result/prob_bert_sent_send_ce_hanthey.txt

python probability_albert.py stimuli/sent_send_ce_eykey.txt result/prob_albert_sent_send_ce_eykey.txt
python probability_albert.py stimuli/sent_send_cehuy_hanthey.txt result/prob_albert_sent_send_cehuy_hanthey.txt
python probability_albert.py stimuli/sent_send_cehuy_eykey.txt result/prob_albert_sent_send_cehuy_eykey.txt
python probability_albert.py stimuli/sent_send_ce_hanthey.txt result/prob_albert_sent_send_ce_hanthey.txt

python probability_xlm_roberta.py stimuli/sent_send_ce_eykey.txt result/prob_xlm_roberta_sent_send_ce_eykey.txt
python probability_xlm_roberta.py stimuli/sent_send_cehuy_hanthey.txt result/prob_xlm_roberta_sent_send_cehuy_hanthey.txt
python probability_xlm_roberta.py stimuli/sent_send_cehuy_eykey.txt result/prob_xlm_roberta_sent_send_cehuy_eykey.txt
python probability_xlm_roberta.py stimuli/sent_send_ce_hanthey.txt result/prob_xlm_roberta_sent_send_ce_hanthey.txt

python cal_word_prob.py result/prob_gpt_sent_send_ce_eykey.txt result/prob_gpt_sent_send_ce_eykey_word.txt
python cal_word_prob.py result/prob_gpt_sent_send_cehuy_hanthey.txt result/prob_gpt_sent_send_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_gpt_sent_send_cehuy_eykey.txt result/prob_gpt_sent_send_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_gpt_sent_send_ce_hanthey.txt result/prob_gpt_sent_send_ce_hanthey_word.txt

python cal_word_prob.py result/prob_bert_sent_send_ce_eykey.txt result/prob_bert_sent_send_ce_eykey_word.txt
python cal_word_prob.py result/prob_bert_sent_send_cehuy_hanthey.txt result/prob_bert_sent_send_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_bert_sent_send_cehuy_eykey.txt result/prob_bert_sent_send_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_bert_sent_send_ce_hanthey.txt result/prob_bert_sent_send_ce_hanthey_wrd.txt

python cal_word_prob.py result/prob_albert_sent_send_ce_eykey.txt result/prob_albert_sent_send_ce_eykey_word.txt
python cal_word_prob.py result/prob_albert_sent_send_cehuy_hanthey.txt result/prob_albert_sent_send_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_albert_sent_send_cehuy_eykey.txt result/prob_albert_sent_send_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_albert_sent_send_ce_hanthey.txt result/prob_albert_sent_send_ce_hanthey_word.txt

python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_send_ce_eykey.txt result/prob_xlm_roberta_sent_send_ce_eykey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_send_cehuy_hanthey.txt result/prob_xlm_roberta_sent_send_cehuy_hanthey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_send_cehuy_eykey.txt result/prob_xlm_roberta_sent_send_cehuy_eykey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_send_ce_hanthey.txt result/prob_xlm_roberta_sent_send_ce_hanthey_word.txt

python cal_accuracy.py result/prob_gpt_sent_send_ce_eykey_word.txt
python cal_accuracy.py result/prob_gpt_sent_send_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_gpt_sent_send_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_gpt_sent_send_ce_hanthey_word.txt
python cal_accuracy.py result/prob_bert_sent_send_ce_eykey_word.txt
python cal_accuracy.py result/prob_bert_sent_send_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_bert_sent_send_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_bert_sent_send_ce_hanthey_wrd.txt
python cal_accuracy.py result/prob_albert_sent_send_ce_eykey_word.txt
python cal_accuracy.py result/prob_albert_sent_send_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_albert_sent_send_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_albert_sent_send_ce_hanthey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_send_ce_eykey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_send_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_send_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_send_ce_hanthey_word.txt

python probability_gpt.py stimuli/sent_give_ce_eykey.txt result/prob_gpt_sent_give_ce_eykey.txt
python probability_gpt.py stimuli/sent_give_cehuy_hanthey.txt result/prob_gpt_sent_give_cehuy_hanthey.txt
python probability_gpt.py stimuli/sent_give_cehuy_eykey.txt result/prob_gpt_sent_give_cehuy_eykey.txt
python probability_gpt.py stimuli/sent_give_ce_hanthey.txt result/prob_gpt_sent_give_ce_hanthey.txt

python probability_bert.py stimuli/sent_give_ce_eykey.txt result/prob_bert_sent_give_ce_eykey.txt
python probability_bert.py stimuli/sent_give_cehuy_hanthey.txt result/prob_bert_sent_give_cehuy_hanthey.txt
python probability_bert.py stimuli/sent_give_cehuy_eykey.txt result/prob_bert_sent_give_cehuy_eykey.txt
python probability_bert.py stimuli/sent_give_ce_hanthey.txt result/prob_bert_sent_give_ce_hanthey.txt

python probability_albert.py stimuli/sent_give_ce_eykey.txt result/prob_albert_sent_give_ce_eykey.txt
python probability_albert.py stimuli/sent_give_cehuy_hanthey.txt result/prob_albert_sent_give_cehuy_hanthey.txt
python probability_albert.py stimuli/sent_give_cehuy_eykey.txt result/prob_albert_sent_give_cehuy_eykey.txt
python probability_albert.py stimuli/sent_give_ce_hanthey.txt result/prob_albert_sent_give_ce_hanthey.txt

python probability_xlm_roberta.py stimuli/sent_give_ce_eykey.txt result/prob_xlm_roberta_sent_give_ce_eykey.txt
python probability_xlm_roberta.py stimuli/sent_give_cehuy_hanthey.txt result/prob_xlm_roberta_sent_give_cehuy_hanthey.txt
python probability_xlm_roberta.py stimuli/sent_give_cehuy_eykey.txt result/prob_xlm_roberta_sent_give_cehuy_eykey.txt
python probability_xlm_roberta.py stimuli/sent_give_ce_hanthey.txt result/prob_xlm_roberta_sent_give_ce_hanthey.txt

python cal_word_prob.py result/prob_gpt_sent_give_ce_eykey.txt result/prob_gpt_sent_give_ce_eykey_word.txt
python cal_word_prob.py result/prob_gpt_sent_give_cehuy_hanthey.txt result/prob_gpt_sent_give_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_gpt_sent_give_cehuy_eykey.txt result/prob_gpt_sent_give_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_gpt_sent_give_ce_hanthey.txt result/prob_gpt_sent_give_ce_hanthey_word.txt

python cal_word_prob.py result/prob_bert_sent_give_ce_eykey.txt result/prob_bert_sent_give_ce_eykey_word.txt
python cal_word_prob.py result/prob_bert_sent_give_cehuy_hanthey.txt result/prob_bert_sent_give_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_bert_sent_give_cehuy_eykey.txt result/prob_bert_sent_give_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_bert_sent_give_ce_hanthey.txt result/prob_bert_sent_give_ce_hanthey_wrd.txt

python cal_word_prob.py result/prob_albert_sent_give_ce_eykey.txt result/prob_albert_sent_give_ce_eykey_word.txt
python cal_word_prob.py result/prob_albert_sent_give_cehuy_hanthey.txt result/prob_albert_sent_give_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_albert_sent_give_cehuy_eykey.txt result/prob_albert_sent_give_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_albert_sent_give_ce_hanthey.txt result/prob_albert_sent_give_ce_hanthey_word.txt

python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_give_ce_eykey.txt result/prob_xlm_roberta_sent_give_ce_eykey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_give_cehuy_hanthey.txt result/prob_xlm_roberta_sent_give_cehuy_hanthey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_give_cehuy_eykey.txt result/prob_xlm_roberta_sent_give_cehuy_eykey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_give_ce_hanthey.txt result/prob_xlm_roberta_sent_give_ce_hanthey_word.txt

python cal_accuracy.py result/prob_gpt_sent_give_ce_eykey_word.txt
python cal_accuracy.py result/prob_gpt_sent_give_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_gpt_sent_give_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_gpt_sent_give_ce_hanthey_word.txt
python cal_accuracy.py result/prob_bert_sent_give_ce_eykey_word.txt
python cal_accuracy.py result/prob_bert_sent_give_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_bert_sent_give_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_bert_sent_give_ce_hanthey_wrd.txt
python cal_accuracy.py result/prob_albert_sent_give_ce_eykey_word.txt
python cal_accuracy.py result/prob_albert_sent_give_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_albert_sent_give_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_albert_sent_give_ce_hanthey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_give_ce_eykey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_give_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_give_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_give_ce_hanthey_word.txt

python probability_gpt.py stimuli/sent_read_ce_eykey.txt result/prob_gpt_sent_read_ce_eykey.txt
python probability_gpt.py stimuli/sent_read_cehuy_hanthey.txt result/prob_gpt_sent_read_cehuy_hanthey.txt
python probability_gpt.py stimuli/sent_read_cehuy_eykey.txt result/prob_gpt_sent_read_cehuy_eykey.txt
python probability_gpt.py stimuli/sent_read_ce_hanthey.txt result/prob_gpt_sent_read_ce_hanthey.txt

python probability_bert.py stimuli/sent_read_ce_eykey.txt result/prob_bert_sent_read_ce_eykey.txt
python probability_bert.py stimuli/sent_read_cehuy_hanthey.txt result/prob_bert_sent_read_cehuy_hanthey.txt
python probability_bert.py stimuli/sent_read_cehuy_eykey.txt result/prob_bert_sent_read_cehuy_eykey.txt
python probability_bert.py stimuli/sent_read_ce_hanthey.txt result/prob_bert_sent_read_ce_hanthey.txt

python probability_albert.py stimuli/sent_read_ce_eykey.txt result/prob_albert_sent_read_ce_eykey.txt
python probability_albert.py stimuli/sent_read_cehuy_hanthey.txt result/prob_albert_sent_read_cehuy_hanthey.txt
python probability_albert.py stimuli/sent_read_cehuy_eykey.txt result/prob_albert_sent_read_cehuy_eykey.txt
python probability_albert.py stimuli/sent_read_ce_hanthey.txt result/prob_albert_sent_read_ce_hanthey.txt

python probability_xlm_roberta.py stimuli/sent_read_ce_eykey.txt result/prob_xlm_roberta_sent_read_ce_eykey.txt
python probability_xlm_roberta.py stimuli/sent_read_cehuy_hanthey.txt result/prob_xlm_roberta_sent_read_cehuy_hanthey.txt
python probability_xlm_roberta.py stimuli/sent_read_cehuy_eykey.txt result/prob_xlm_roberta_sent_read_cehuy_eykey.txt
python probability_xlm_roberta.py stimuli/sent_read_ce_hanthey.txt result/prob_xlm_roberta_sent_read_ce_hanthey.txt

python cal_word_prob.py result/prob_gpt_sent_read_ce_eykey.txt result/prob_gpt_sent_read_ce_eykey_word.txt
python cal_word_prob.py result/prob_gpt_sent_read_cehuy_hanthey.txt result/prob_gpt_sent_read_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_gpt_sent_read_cehuy_eykey.txt result/prob_gpt_sent_read_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_gpt_sent_read_ce_hanthey.txt result/prob_gpt_sent_read_ce_hanthey_word.txt

python cal_word_prob.py result/prob_bert_sent_read_ce_eykey.txt result/prob_bert_sent_read_ce_eykey_word.txt
python cal_word_prob.py result/prob_bert_sent_read_cehuy_hanthey.txt result/prob_bert_sent_read_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_bert_sent_read_cehuy_eykey.txt result/prob_bert_sent_read_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_bert_sent_read_ce_hanthey.txt result/prob_bert_sent_read_ce_hanthey_wrd.txt

python cal_word_prob.py result/prob_albert_sent_read_ce_eykey.txt result/prob_albert_sent_read_ce_eykey_word.txt
python cal_word_prob.py result/prob_albert_sent_read_cehuy_hanthey.txt result/prob_albert_sent_read_cehuy_hanthey_word.txt
python cal_word_prob.py result/prob_albert_sent_read_cehuy_eykey.txt result/prob_albert_sent_read_cehuy_eykey_word.txt
python cal_word_prob.py result/prob_albert_sent_read_ce_hanthey.txt result/prob_albert_sent_read_ce_hanthey_word.txt

python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_read_ce_eykey.txt result/prob_xlm_roberta_sent_read_ce_eykey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_read_cehuy_hanthey.txt result/prob_xlm_roberta_sent_read_cehuy_hanthey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_read_cehuy_eykey.txt result/prob_xlm_roberta_sent_read_cehuy_eykey_word.txt
python cal_word_prob_xlm.py result/prob_xlm_roberta_sent_read_ce_hanthey.txt result/prob_xlm_roberta_sent_read_ce_hanthey_word.txt

python cal_accuracy.py result/prob_gpt_sent_read_ce_eykey_word.txt
python cal_accuracy.py result/prob_gpt_sent_read_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_gpt_sent_read_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_gpt_sent_read_ce_hanthey_word.txt
python cal_accuracy.py result/prob_bert_sent_read_ce_eykey_word.txt
python cal_accuracy.py result/prob_bert_sent_read_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_bert_sent_read_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_bert_sent_read_ce_hanthey_wrd.txt
python cal_accuracy.py result/prob_albert_sent_read_ce_eykey_word.txt
python cal_accuracy.py result/prob_albert_sent_read_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_albert_sent_read_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_albert_sent_read_ce_hanthey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_read_ce_eykey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_read_cehuy_hanthey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_read_cehuy_eykey_word.txt
python cal_accuracy.py result/prob_xlm_roberta_sent_read_ce_hanthey_word.txt


